name: DSP_APP
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2025.10.5=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - expat=2.7.1=h8ddb27b_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - networkx=3.5=py311haa95532_0
  - numpy-base=2.0.1=py311hd01c5d8_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - pycparser=2.23=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - requests=2.32.5=py311haa95532_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - aenum==3.1.16
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - eval-type-backport==0.2.2
      - faster-coco-eval==1.7.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightly==1.5.22
      - lightly-train==0.11.4
      - lightly-utils==0.0.2
      - lightning-utilities==0.15.2
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - multidict==6.7.0
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.2
      - pyarrow==22.0.0
      - pycocotools==2.0.10
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - regex==2025.10.23
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentry-sdk==2.43.0
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - stringzilla==4.2.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.21
      - tokenizers==0.22.1
      - torchaudio==2.5.1
      - torchmetrics==1.8.2
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-inspection==0.4.2
      - ultralytics==8.3.223
      - ultralytics-thop==2.0.18
      - wandb==0.22.3
      - werkzeug==3.1.3
      - yarl==1.22.0
prefix: C:\Users\HoangNam\miniconda3\envs\DSP_APP
